import 'dart:developer';

import 'package:wallet_app/core/helpers/api_helper.dart';
import 'package:wallet_app/core/models/autogenerated_model.dart';
import 'package:wallet_app/features/auth/login/data/repo/login_repo.dart';

class LoginImp implements LoginRepo {
  final ApiHelper apiHelper;

  LoginImp({required this.apiHelper});
  @override
  Future<Autogenerated> login({
    required String email,
    required String password,
  }) async {
    try {
      Map<String , dynamic> response = await apiHelper.post(
        endPoint: "users/login",
        body: {"email": email, "password": password},
      );
      log(response.toString());
      return Autogenerated.fromJson(response);
    } catch (e) {
      log(e.toString());
      return Autogenerated();
    }
  }
}
