import 'package:wallet_app/core/models/user_model.dart';

class Autogenerated {
  String? message;
  int? exp;
  String? token;
  User? user;

  Autogenerated({this.message, this.exp, this.token, this.user});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      message: json["message"],
      exp: json['exp'],
      token: json["token"],
      user: User.fromJson(json["user"]),
    );
  }

  Map<String, dynamic> toJson() {
    return {"message": message, "exp": exp, "token": token, "user": user};
  }
}
